In [10]:
import numpy as np

#numpy array normal
arr = np.array([1,2,3])
print(arr)

#numpy array matriz
mtz = np.array([[1,2,3],[4,5,6],[7,8,9]])

#numpy array normal tudo igual
i= np.zeros(5)

#numpy array matriz tudo igual
m= np.ones([3,3])

print(arr)
print(mtz)
print(i)
print(m)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
